---
title: "About R Views Too"
about:
  template: trestles
---

Welcome to R Views Too, the upgraded and enhanced version of [R Views](https://rviews.rstudio.com).

R Views Too is the Posit blog devoted to the R Community and the R Language. We imagine it as a place to read considered opinions about topics of interest to the R Community, get some idea of what is happening at conferences and user group meetings around the world, learn about new R packages, see R used to explore various areas of statistics or data science, and discover how Posit tools can contribute to enhancing your R experience.

R Views Too is powered by [Quarto](https://quarto.org/). We moved to this new platform to provide an enhanced experience for our readers. With Quarto's advanced features, we can better showcase R-related topics and deliver high-quality content.

The blog is edited by Joseph Rickert and [Isabella Velásquez](https://twitter.com/ivelasq3), who curate the content and ensure its quality. In addition to posts written by the Posit team, we hope that R Views Too will continue to attract other voices from around the R Community. If you have something to say on an R-related topic, news, commentary, or an example of using R that you would like to share with the R Community, please review the [How to](./how-to-contribute.html) page and email your ideas to [rviewstoo@posit.co](mailto:rviewstoo@posit.co).

R Views Too is a new beginning built around a Quarto, a publishing platform that we expect will prove to be a great benefit to scientific and technical publishing in general. Although R Views Too will launch with all new posts, we expect that a good number, if not all R Views posts, will be eventually ported over to R Views Too. In the meantime, your favorite posts will continue to be available at [https://rviews.rstudio.com/](https://rviews.rstudio.com/).

Note that R Views Too is not the place to look for news or information on Posit products or events. The widely syndicated blog at [posit.co](https://posit.co/blog) will remain the place for Posit open source and commercial product announcements, company events, and company news.

We welcome comments from all readers and encourage discussion on [Posit Community](https://community.posit.co/). However, comments will not be moderated. Please be courteous and civil.
